"""empty message

Revision ID: 172168213052
Revises: 45e662dbee85
Create Date: 2014-09-27 15:29:40.034000

"""

# revision identifiers, used by Alembic.
revision = '172168213052'
down_revision = '45e662dbee85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'date_created')
    op.create_unique_constraint(None, 'user', ['page_domain'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.add_column('history', sa.Column('date_created', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
