"""empty message

Revision ID: 24a1367bf8d9
Revises: c421e507957
Create Date: 2014-09-28 13:30:56.720000

"""

# revision identifiers, used by Alembic.
revision = '24a1367bf8d9'
down_revision = 'c421e507957'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
