"""empty message

Revision ID: 45e662dbee85
Revises: 579a6a542521
Create Date: 2014-09-27 15:05:26.709000

"""

# revision identifiers, used by Alembic.
revision = '45e662dbee85'
down_revision = '579a6a542521'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('date_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'date_created')
    ### end Alembic commands ###
