"""empty message

Revision ID: c421e507957
Revises: 172168213052
Create Date: 2014-09-28 12:49:19.231000

"""

# revision identifiers, used by Alembic.
revision = 'c421e507957'
down_revision = '172168213052'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img_key', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img_key')
    ### end Alembic commands ###
